# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: ENV['WEBAPP_DEV_DATABASE']
  username: ENV['WEBAPP_DEV_USERNAME']
  password: ENV['WEBAPP_DEV_PASSWORD']
  host:     ENV['WEBAPP_DEV_HOST']
  port:     ENV['WEBAPP_DEV_PORT']

production:
  adaptor: postgresql
  encoding: unicode
  pool: 5
  database: ENV['WEBAPP_PROD_DATABASE']
  username: ENV['WEBAPP_PROD_USERNAME']
  password: ENV['WEBAPP_PROD_PASSWORD']
  host:     ENV['WEBAPP_PROD_HOST']
  port:     ENV['WEBAPP_PROD_PORT']
